apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: default
  labels:
    app: frontend
    component: config
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        
        location / {
            proxy_pass http://internal-k8s-default-backendi-718e8edf4e-560304442.eu-central-1.elb.amazonaws.com/api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            add_header X-Frontend-Pod $hostname;
        }
        
        location /health {
            add_header Content-Type text/plain;
            return 200 'Frontend OK\n';
        }
        
        location /version {
            add_header Content-Type text/plain;
            return 200 'Frontend: $hostname\n';
        }
    }
